<?xml version="1.0" encoding="utf-8"?>
<test-run id="0" testcasecount="21" result="Failed" total="21" passed="0" failed="21" inconclusive="0" skipped="0" asserts="2" portable-engine-version="3.3.0.0" start-time="2016-10-20 15:59:30Z" end-time="2016-10-20 15:59:31Z" duration="1.509773">
  <test-suite type="Assembly" id="1033" name="tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" fullname="tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" runstate="Runnable" testcasecount="21" result="Failed" site="Child" start-time="2016-10-20 15:59:30Z" end-time="2016-10-20 15:59:31Z" duration="1.154356" total="21" passed="0" failed="21" inconclusive="0" skipped="0" asserts="2">
    <settings>
      <setting name="WorkDirectory" value="E:\Projects\EthereumApiDotNetCore\tests" />
    </settings>
    <properties>
      <property name="ParallelScope" value="None" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="SetUpFixture" id="1024" name="Tests" fullname="Tests.Config" classname="Tests.Config" runstate="Runnable" testcasecount="21" result="Failed" label="Error" site="SetUp" start-time="2016-10-20 15:59:30Z" end-time="2016-10-20 15:59:31Z" duration="1.109951" total="21" passed="0" failed="21" inconclusive="0" skipped="0" asserts="2">
      <failure>
        <message><![CDATA[System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        <stack-trace><![CDATA[   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Tests.Config.<Initialize>d__8.MoveNext() in E:\Projects\EthereumApiDotNetCore\tests\Init\Config.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunAsyncMethod(MethodInfo method, TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.OneTimeSetUpCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()]]></stack-trace>
      </failure>
      <test-suite type="TestFixture" id="1000" name="BigDecimalTests" fullname="Tests.BigDecimalTests" classname="Tests.BigDecimalTests" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1001" name="TestDivide" fullname="Tests.BigDecimalTests.TestDivide" methodname="TestDivide" classname="Tests.BigDecimalTests" runstate="Runnable" seed="1143464689" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1002" name="TestMultuple" fullname="Tests.BigDecimalTests.TestMultuple" methodname="TestMultuple" classname="Tests.BigDecimalTests" runstate="Runnable" seed="305808271" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1003" name="ContractQueueServiceTests" fullname="Tests.ContractQueueServiceTests" classname="Tests.ContractQueueServiceTests" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1004" name="TestPushAndGetContract" fullname="Tests.ContractQueueServiceTests.TestPushAndGetContract" methodname="TestPushAndGetContract" classname="Tests.ContractQueueServiceTests" runstate="Runnable" seed="1706747668" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1005" name="TestSaveUserContract" fullname="Tests.ContractQueueServiceTests.TestSaveUserContract" methodname="TestSaveUserContract" classname="Tests.ContractQueueServiceTests" runstate="Runnable" seed="953776648" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1006" name="EthereumQueueOutTests" fullname="Tests.EthereumQueueOutTests" classname="Tests.EthereumQueueOutTests" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1007" name="TestFirePaymentEvent" fullname="Tests.EthereumQueueOutTests.TestFirePaymentEvent" methodname="TestFirePaymentEvent" classname="Tests.EthereumQueueOutTests" runstate="Runnable" seed="1121776128" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1008" name="JaascriptTestData" fullname="Tests.JaascriptTestData" classname="Tests.JaascriptTestData" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1009" name="Data" fullname="Tests.JaascriptTestData.Data" methodname="Data" classname="Tests.JaascriptTestData" runstate="Runnable" seed="1559751847" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1010" name="Test22" fullname="Tests.JaascriptTestData.Test22" methodname="Test22" classname="Tests.JaascriptTestData" runstate="Runnable" seed="1769003176" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestSuite" id="1035" name="JobTests" fullname="Tests.JobTests" runstate="Runnable" testcasecount="4" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-suite type="TestFixture" id="1025" name="CheckPaymentsToUserContractsJobTests" fullname="Tests.JobTests.CheckPaymentsToUserContractsJobTests" classname="Tests.JobTests.CheckPaymentsToUserContractsJobTests" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1026" name="TestCheckPaymentsToUserContractsJobExecute" fullname="Tests.JobTests.CheckPaymentsToUserContractsJobTests.TestCheckPaymentsToUserContractsJobExecute" methodname="TestCheckPaymentsToUserContractsJobExecute" classname="Tests.JobTests.CheckPaymentsToUserContractsJobTests" runstate="Runnable" seed="705417056" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1029" name="MonitoringJobTests" fullname="Tests.JobTests.MonitoringJobTests" classname="Tests.JobTests.MonitoringJobTests" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1030" name="TestMonitoringJobExecute" fullname="Tests.JobTests.MonitoringJobTests.TestMonitoringJobExecute" methodname="TestMonitoringJobExecute" classname="Tests.JobTests.MonitoringJobTests" runstate="Runnable" seed="641676517" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1027" name="TestMonitoringContractBalanceJob" fullname="Tests.JobTests.TestMonitoringContractBalanceJob" classname="Tests.JobTests.TestMonitoringContractBalanceJob" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1028" name="TestMonitoringContractBalanceJobExecute" fullname="Tests.JobTests.TestMonitoringContractBalanceJob.TestMonitoringContractBalanceJobExecute" methodname="TestMonitoringContractBalanceJobExecute" classname="Tests.JobTests.TestMonitoringContractBalanceJob" runstate="Runnable" seed="1857320908" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1031" name="TransferTransactionQueueJobTests" fullname="Tests.JobTests.TransferTransactionQueueJobTests" classname="Tests.JobTests.TransferTransactionQueueJobTests" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1032" name="TestTransferTransactionExecute" fullname="Tests.JobTests.TransferTransactionQueueJobTests.TestTransferTransactionExecute" methodname="TestTransferTransactionExecute" classname="Tests.JobTests.TransferTransactionQueueJobTests" runstate="Runnable" seed="800080964" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1011" name="PaymentServiceTests" fullname="Tests.PaymentServiceTests" classname="Tests.PaymentServiceTests" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1012" name="TestGetMainBalance" fullname="Tests.PaymentServiceTests.TestGetMainBalance" methodname="TestGetMainBalance" classname="Tests.PaymentServiceTests" runstate="Runnable" seed="605227096" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1013" name="TestTransferFromUserContract" fullname="Tests.PaymentServiceTests.TestTransferFromUserContract" methodname="TestTransferFromUserContract" classname="Tests.PaymentServiceTests" runstate="Runnable" seed="331480127" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1014" name="TestCoins" fullname="Tests.TestCoins" classname="Tests.TestCoins" runstate="Runnable" testcasecount="5" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1015" name="TestCashin" fullname="Tests.TestCoins.TestCashin" methodname="TestCashin" classname="Tests.TestCoins" runstate="Runnable" seed="867300776" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1016" name="TestCashout" fullname="Tests.TestCoins.TestCashout" methodname="TestCashout" classname="Tests.TestCoins" runstate="Runnable" seed="2050980388" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1019" name="TestCoinEvents" fullname="Tests.TestCoins.TestCoinEvents" methodname="TestCoinEvents" classname="Tests.TestCoins" runstate="Runnable" seed="427345585" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1018" name="TestCoinSwap" fullname="Tests.TestCoins.TestCoinSwap" methodname="TestCoinSwap" classname="Tests.TestCoins" runstate="Runnable" seed="921146316" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1017" name="TestTransfer" fullname="Tests.TestCoins.TestTransfer" methodname="TestTransfer" classname="Tests.TestCoins" runstate="Runnable" seed="1250837361" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-suite type="TestFixture" id="1020" name="TestContracts" fullname="Tests.TestContracts" classname="Tests.TestContracts" runstate="Runnable" testcasecount="3" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-suite>
      <test-case id="1023" name="TestRefillAccount" fullname="Tests.TestContracts.TestRefillAccount" methodname="TestRefillAccount" classname="Tests.TestContracts" runstate="Runnable" seed="906648926" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1021" name="TestUserContractBigAmount" fullname="Tests.TestContracts.TestUserContractBigAmount" methodname="TestUserContractBigAmount" classname="Tests.TestContracts" runstate="Runnable" seed="598925335" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
      <test-case id="1022" name="TestUserContractWrongSender" fullname="Tests.TestContracts.TestUserContractWrongSender" methodname="TestUserContractWrongSender" classname="Tests.TestContracts" runstate="Runnable" seed="2074112374" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
        <failure>
          <message><![CDATA[OneTimeSetUp: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
        </failure>
      </test-case>
    </test-suite>
  </test-suite>
</test-run>